version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=software_developer_challenge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ali1234
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
